XCODE_DIR = ~/Library/Developer/Xcode/UserData/CodeSnippets
SNIPPETS_DIR = ./

install:
	mkdir -p $(XCODE_DIR)
	cp $(SNIPPETS_DIR)/GuardLet.codesnippet $(XCODE_DIR)
	cp $(SNIPPETS_DIR)/LetStackView.codesnippet $(XCODE_DIR)
	cp $(SNIPPETS_DIR)/LetUIButton.codesnippet $(XCODE_DIR)
	cp $(SNIPPETS_DIR)/LetUIImageView.codesnippet $(XCODE_DIR)
	cp $(SNIPPETS_DIR)/LetUILabel.codesnippet $(XCODE_DIR)
	cp $(SNIPPETS_DIR)/LetUITextField.codesnippet $(XCODE_DIR)
	cp $(SNIPPETS_DIR)/LetUIView.codesnippet $(XCODE_DIR)
	cp $(SNIPPETS_DIR)/MarkComment.codesnippet $(XCODE_DIR)
	cp $(SNIPPETS_DIR)/SeeAlsoComment.codesnippet $(XCODE_DIR)
	cp $(SNIPPETS_DIR)/ObjcAction.codesnippet $(XCODE_DIR)

uninstall:
	rm -f $(XCODE_DIR)/GuardLet.codesnippet 
	rm -f $(XCODE_DIR)/LetStackView.codesnippet 
	rm -f $(XCODE_DIR)/LetUIButton.codesnippet 
	rm -f $(XCODE_DIR)/LetUIImageView.codesnippet 
	rm -f $(XCODE_DIR)/LetUILabel.codesnippet 
	rm -f $(XCODE_DIR)/LetUITextField.codesnippet
	rm -f $(XCODE_DIR)/LetUIView.codesnippet
	rm -f $(XCODE_DIR)/MarkComment.codesnippet
	rm -f $(XCODE_DIR)/SeeAlsoComment.codesnippet
	rm -f $(XCODE_DIR)/ObjcAction.codesnippet

update_snippets_from_xcode: 
	cp $(XCODE_DIR)/GuardLet.codesnippet $(SNIPPETS_DIR)
	cp $(XCODE_DIR)/LetStackView.codesnippet $(SNIPPETS_DIR)
	cp $(XCODE_DIR)/LetUIButton.codesnippet $(SNIPPETS_DIR)
	cp $(XCODE_DIR)/LetUIImageView.codesnippet $(SNIPPETS_DIR)
	cp $(XCODE_DIR)/LetUILabel.codesnippet $(SNIPPETS_DIR)
	cp $(XCODE_DIR)/LetUITextField.codesnippet $(SNIPPETS_DIR)
	cp $(XCODE_DIR)/LetUIView.codesnippet $(SNIPPETS_DIR)
	cp $(XCODE_DIR)/MarkComment.codesnippet $(SNIPPETS_DIR)
	cp $(XCODE_DIR)/SeeAlsoComment.codesnippet $(SNIPPETS_DIR)
	cp $(XCODE_DIR)/ObjcAction.codesnippet $(SNIPPETS_DIR)
