XCODE_TEMPLATES_DIR = ~/Library/Developer/Xcode/Templates
TEMPLATES_DIR = ./

install:
	mkdir -p $(XCODE_TEMPLATES_DIR)
	cp -r $(TEMPLATES_DIR)/MVVM.xctemplate $(XCODE_TEMPLATES_DIR)

uninstall:
	rm -f $(TEMPLATES_DIR)/MVVM.xctemplate
